apiVersion: apps/v1
kind: Deployment
# Labels for deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
# Labels for pod (app/container)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
# Labels for exposing app (service)
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80