apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    env: dev
spec:
  containers:
  - name: apache
    image: httpd:latest
  nodeSelector:
    type: webserver

    ## kubectl describe pods apache
    ## kubectl label node kube-node-02 type=webserver