apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: dev
spec:
   containers:
     - name: nginx
       image: nginx:latest
   affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In
              values:
              - large
              - small



## kubectl label node kube-node-01 size=large