apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1 # You must define a weight for preferences
          preference:
            matchExpressions:
              - key: size
                operator: In
                values:
                  - large
                  - small
